
toolingnamespace: tooling
jenkinsApplicationName: jenkins-app
jenkinsimage:
  name: 416591745024.dkr.ecr.eu-west-2.amazonaws.com/personal-jenkins-repo/jenkins-application
  tag: "latest"

jenkinsservice: jenkins-app-service
serviceingress:  jenkins-ingress-service
jenkinsappbaseURL : jenkins.globalfrontierlink.co.uk