apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkinsservice }}
  namespace: {{ .Values.toolingnamespace }}
spec:
  selector:
    app: {{ .Values.jenkinsApplicationName }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
